import thumunsJson from "./quran-thumuns.json";
import surahsJson from "./quran-surahs.json";
import recitersJson from "./audio-reciters.json";

/**
 * Qur'an division data — 480 أثمان per the Maghrebi division
 * (60 حزباً × 8 أثمان) of the Mushaf al-Muhammadi (Warsh 'an Nafi').
 * Generated by `scripts/generate-thumuns.mjs` — see README for provenance.
 */
export interface Thumun {
  id: number;
  juz: number;
  hizb: number;
  pos: number; // 1..8 within the hizb
  name: string; // الثمن الأول | الربع | ثلاثة أثمان | النصف | ...
  startSura: number;
  startAya: number;
  endSura: number;
  endAya: number;
  partialStart: boolean; // begins mid-ayah
  partialEnd: boolean; // ends mid-ayah
  verses: number;
  words: number;
  isSuraStart: boolean;
  text: string; // start snippet (Warsh rasm)
  pages: [number, number];
}

export interface SurahInfo {
  number: number;
  name: string;
  nameTranslit: string;
  revelation: "makki" | "madani";
  verses: number;
  words: number;
  firstEighth: number;
  lastEighth: number;
}

export interface Reciter {
  id: string;
  name: string;
  nameEn: string;
  country: string;
  server: string;
  recommended: boolean;
}

export type EditedThumun = Partial<
  Pick<Thumun, "startSura" | "startAya" | "endSura" | "endAya" | "text">
>;
export type EditedThumuns = Record<number, EditedThumun>;

const thumuns = (thumunsJson as unknown as { thumuns: Thumun[] }).thumuns;
const surahs = (surahsJson as { surahs: SurahInfo[] }).surahs;
const reciterData = recitersJson as {
  urlPattern: string;
  reciters: Reciter[];
};

export const TOTAL_THUMUNS = 480;
export const THUMUNS_PER_HIZB = 8;
export const THUMUNS_PER_JUZ = 16;
export const TOTAL_HIZBS = 60;
export const TOTAL_JUZS = 30;
export const TOTAL_SURAHS = 114;

const surahByNumber = new Map(surahs.map((s) => [s.number, s]));

export function getThumun(id: number, edited?: EditedThumuns): Thumun | null {
  if (id < 1 || id > TOTAL_THUMUNS) return null;
  const base = thumuns[id - 1];
  if (!base) return null;
  const edit = edited?.[id];
  return edit ? { ...base, ...edit } : base;
}

export function getAllThumuns(): Thumun[] {
  return thumuns;
}

export function getSurah(n: number): SurahInfo | null {
  return surahByNumber.get(n) ?? null;
}

export function getAllSurahs(): SurahInfo[] {
  return surahs;
}

export function getReciters(): Reciter[] {
  return reciterData.reciters;
}

/** Per-surah MP3 URL for a Warsh reciter (001.mp3 .. 114.mp3). */
export function surahAudioUrl(reciter: Reciter, sura: number): string {
  return `${reciter.server}${String(sura).padStart(3, "0")}.mp3`;
}
