"use client";
import { Award, BarChart3, BookOpen, BookOpenCheck, Castle, CheckCircle2, Clock, Coins, Flame, Flower2, Gem, Hammer, Mountain, Shield, Sparkles, Sprout, Trophy } from "lucide-react";
import { useState } from "react";
import { formatNum } from "@/lib/format";
import { MILESTONES, SPECIAL_ACHIEVEMENTS } from "@/lib/constants";
import { progressMetrics } from "@/lib/progress/derive";
import { useHifzStore } from "@/store/useHifzStore";
import ActivityHeatmap from "./ActivityHeatmap";
import JourneyRoadmap from "./JourneyRoadmap";

type StatsView = "map" | "milestones" | "activity";

export default function StatsDashboard() {
  const data = useHifzStore();
  const metrics = progressMetrics(data);
  const arabic = data.settings.arabicNumerals;
  const [view, setView] = useState<StatsView>("map");
  const sessions = Object.values(data.sessions);
  const minutes = Math.floor(sessions.reduce((total, session) => total + session.seconds, 0) / 60);
  const score = { bestStreak: data.bestStreak, perfectDays: metrics.perfectDays, totalXp: data.totalXp, highestDay: metrics.highest, zahrawayn: metrics.zahrawayn, sessionMinutes: minutes };
  const earned = MILESTONES.filter((milestone) => milestone.threshold === 480 ? metrics.count === 480 : metrics.juzs.length >= milestone.threshold / 16);
  const next = MILESTONES.find((milestone) => !earned.includes(milestone));
  const recent = [...sessions].sort((a, b) => b.at.localeCompare(a.at)).slice(0, 12);
  const cards = [{ title: "أثمان محفوظة", value: metrics.count, icon: BookOpen }, { title: "أيام ورد مكتملة", value: metrics.perfectDays, icon: CheckCircle2 }, { title: "سلسلة النشاط", value: data.streak, icon: Flame }, { title: "أفضل سلسلة", value: data.bestStreak, icon: Trophy }, { title: "النقاط", value: data.totalXp, icon: BarChart3 }, { title: "دقائق الدراسة", value: minutes, icon: Clock }];
  const tabs: { id: StatsView; label: string; icon: typeof BookOpen }[] = [{ id: "map", label: "خريطة الأحزاب", icon: BookOpen }, { id: "milestones", label: "المراحل والشارات", icon: Trophy }, { id: "activity", label: "تقويم النشاط", icon: BookOpenCheck }];
  const achievementIcons = { flame: Flame, shield: Shield, castle: Castle, hammer: Hammer, coins: Coins, sparkles: Sparkles, flower: Flower2, clock: Clock };
  const milestoneIcons = { sprout: Sprout, shield: Shield, medal: Award, award: Award, gem: Gem, crown: Trophy, mountain: Mountain, book: BookOpen };

  return <div className="space-y-5">
    <header className="rounded-[1.75rem] border border-[#a4772b]/30 bg-[#fffdf8] p-5 shadow-sm"><p className="text-xs font-semibold tracking-wide text-[#a4772b]">سجل الرحلة</p><h1 className="mt-1 text-2xl font-bold">إحصائياتك</h1><p className="mt-2 text-sm leading-relaxed text-muted-foreground">نظرة هادئة على ما حفظته، وما داومت عليه، وما يستحق عودتك اليوم.</p></header>
    <div className="grid grid-cols-2 gap-3">{cards.map(({ title, value, icon: Icon }, index) => <section key={title} className={`surface-card p-4 space-y-2 ${index === 0 ? "border-primary/50 bg-primary/5" : ""}`}><Icon className="size-5 text-primary" aria-hidden /><p className="break-all text-2xl font-bold">{formatNum(value, arabic)}</p><h2 className="text-sm text-muted-foreground">{title}</h2></section>)}</div>
    <p className="text-xs leading-relaxed text-muted-foreground">النشاط: إنجاز جديد أو محاولة مراجعة فردية أو جلسة فعلية 30 ثانية فأكثر. يوم راحة واحد يحافظ على السلسلة ولا يضيف يومًا إليها.</p>
    {data.legacyXp > 0 && <p className="rounded-xl bg-surface p-3 text-sm text-muted-foreground">{formatNum(data.legacyXp, arabic)} نقطة رصيد قديم محفوظ دون مضاعفة. الإنجازات القديمة ليست دليلًا على اكتمال أيام التقويم.</p>}
    <div className="surface-card sticky top-2 z-10 grid grid-cols-3 gap-1 p-1" role="tablist" aria-label="أقسام الإحصائيات">{tabs.map(({ id, label, icon: Icon }) => <button key={id} type="button" role="tab" aria-selected={view === id} aria-controls={`stats-panel-${id}`} className={`flex min-h-11 items-center justify-center gap-1 rounded-xl px-2 text-xs font-semibold transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-primary ${view === id ? "bg-primary text-primary-foreground shadow-sm" : "text-muted-foreground hover:bg-surface"}`} onClick={() => setView(id)}><Icon className="size-4 shrink-0" aria-hidden /><span>{label}</span></button>)}</div>
    {view === "map" && <div id="stats-panel-map" role="tabpanel" tabIndex={0}><JourneyRoadmap memorized={metrics.ids} currentDay={data.currentDay} /></div>}
    {view === "milestones" && <div id="stats-panel-milestones" role="tabpanel" tabIndex={0} className="space-y-5"><section className="surface-card p-5"><div className="flex items-end justify-between gap-3"><div><h2 className="text-lg font-bold">مراحل المحفوظ</h2><p className="mt-1 text-sm text-muted-foreground">{formatNum(metrics.juzs.length, arabic)}/30 جزء · {formatNum(metrics.hizbs.length, arabic)}/60 حزب مكتمل</p></div><BookOpen className="size-6 text-primary" aria-hidden /></div><div className="relative mt-6 space-y-0 before:absolute before:bottom-5 before:right-[13px] before:top-5 before:w-px before:bg-border">{MILESTONES.map((milestone) => { const complete = earned.includes(milestone), Icon = milestoneIcons[milestone.icon]; return <article key={milestone.id} className="relative flex gap-3 py-2"><span className={`z-[1] mt-1 grid size-7 shrink-0 place-items-center rounded-full border-2 bg-card ${complete ? "border-primary bg-primary text-primary-foreground" : "border-border text-muted-foreground"}`} aria-hidden><Icon className="size-4" /></span><div className={`min-w-0 grow rounded-xl border p-3 ${complete ? "border-primary/40 bg-primary/5" : "border-border bg-surface"}`}><div className="flex items-start justify-between gap-2"><h3 className="text-sm font-bold">{milestone.label}</h3><span className="shrink-0 text-xs text-muted-foreground">{formatNum(milestone.threshold / 16, arabic)} أجزاء</span></div><p className="mt-1 text-xs text-muted-foreground">{complete ? "محطة مكتملة" : "المحطة التالية في رحلتك"}</p></div></article>; })}</div>{next && <p className="mt-4 text-sm">المرحلة التالية: {next.label}. تحتاج {formatNum(Math.max(0, next.threshold / 16 - metrics.juzs.length), arabic)} أجزاء كاملة أخرى.</p>}</section><section className="surface-card p-5"><h2 className="text-lg font-bold">شارات النشاط والرسوخ</h2><div className="mt-4 grid grid-cols-2 gap-2">{SPECIAL_ACHIEVEMENTS.map((item) => { const Icon = achievementIcons[item.icon]; return <article key={item.id} className={`rounded-xl border p-3 ${item.check(score) ? "border-primary bg-primary/10" : "border-border bg-surface"}`}><Icon className={`size-6 ${item.check(score) ? "text-primary" : "text-muted-foreground"}`} aria-hidden /><h3 className="mt-1 text-sm font-bold">{item.label}</h3><p className="mt-1 text-xs text-muted-foreground">{item.description}</p></article>; })}</div></section></div>}
    {view === "activity" && <div id="stats-panel-activity" role="tabpanel" tabIndex={0} className="space-y-5"><ActivityHeatmap /><section className="surface-card p-5 space-y-3"><h2 className="text-lg font-bold">آخر جلسات الدراسة</h2>{recent.length ? <ul className="space-y-2">{recent.map((session) => <li key={session.id} className="rounded-xl bg-surface p-3 text-sm"><b>{session.task === "free_review" ? "تثبيت / دراسة حرة" : session.task === "new_hifz" ? "حفظ" : session.task === "prep_weekly" ? "تحضير" : "ورد أو مراجعة"}</b><span className="mt-1 block text-xs text-muted-foreground">{session.date} · محطة {formatNum(session.day, arabic)} · {formatNum(Math.floor(session.seconds / 60), arabic)} دقيقة و{formatNum(session.seconds % 60, arabic)} ثانية{session.abandoned ? " · توقفت دون إتمام الورد" : ""}</span></li>)}</ul> : <p className="text-sm text-muted-foreground">لم تُسجّل جلسات مؤقتة بعد. العلامات اليدوية لا تختلق وقت دراسة.</p>}</section></div>}
  </div>;
}
